### ISSUE TITLE
PgtServer issues

### ISSUE THREAD

**Issue by rxsands** [appdevdesigns/passport-cas#1]
I get a runtime exception when trying to create a PGT callback server because the PgtServer function is trying to use options.serverKey and options.serverCertificate - options is undefined in this function.

**Comment by rxsands** [comment]
Also please note that there is an issue in this line:

req.session[self.casSessionKey].PGTIOU = extended.PGTIOU;

The session key does not exist so this causes an exception.

**Comment by joshAppDev** [comment]
Thanks for catching those. It should be fixed now.

**Comment by rxsands** [comment]
Thanks, I'm glad to help.  This Node.js module is coming in handy for me as
I have to integrate CAS with a Node.js (Express/Passport) application.

I do have a question about passport-cas (or passport-cas2) usage, if you
have a moment.  I'm going to need to get a proxy ticket via the function:
CasStrategy.prototype.getProxyTicket = function(req, targetService, done).
I'm just not sure about where this might call that function.  I am
considering either:
1. In the "verify callback" for CasStrategy.  The problem here is that the
   method signature: function(username, profile, done) does not pass in the
   "req".  I was considering augmenting passport-cas2 to have a parameter like
   passReqToCallback to pass "req" first, so function(req, username, profile,
   done) - see here for documentation:
   http://passportjs.org/docs#association-in-verify-callback
2. In a custom callback that happens _after_ verify, like this:
   http://passportjs.org/docs#custom-callback

Just wondering if you have a vision on where the getProxyTicket function
might be used.  I know it may vary amongst applications...

Thanks,

Richard
