### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN unless set CA in globalAgent

### ISSUE THREAD

**Issue by rxsands** [appdevdesigns/passport-cas#3]
I receive an SSL handshake error using this module unless I set the trusted CAs globally like:

https.globalAgent.options.ca = caCerts;

I have even started to use the sslCA parameter in order to trust the PGT callback server.  I think that underneath the covers, there are other HTTPS requests (such as https.get) that don't pass the "ca" option.

As a workaround I can use the globalAgent, of course.

**Comment by joshAppDev** [comment]
The underlying HTTPS requests to the PGT callback server should have been using the CA option that you specified. The only reason I can think of for why it didn't work is that the `cas` module dependancy on your install didn't get updated automatically together with `passport-cas2`. The project for that `cas` module (also done by me) is here: https://github.com/joshchan/node-cas. In case you want to verify if yours is the latest version.

In any case, I have now updated it to apply the CA option to both the CAS server as well as the PGT callback server. Previously it only did so for the PGT callback server.
