### ISSUE TITLE
Can I set the return url for login?

### ISSUE THREAD

**Issue by imnovaklu** [appdevdesigns/passport-cas#7]
When it redirects to the login form, the url is always "login?service=http://localhost:9000", but I want to change it to "login?service=http://localhost:9000/somepath".

How can I do that?

**Comment by joshAppDev** [comment]
Sorry for missing this earlier. You probably already figured this out, but here's an answer for anyone else who might come across this in the future.

The url used for the `service` parameter is the current url when the authenticate() function gets called, as determined from the `req` object. So before that happens you can change req.url or req.originalUrl and that should become the new `service`. Note that that new url must also be covered by the same authentication strategy.
